version: '3.7'

services:
  openldap: 
    #image: openldap
    image: 192.87.106.18:56001/openldap:0.1
    deploy:
      replicas: 1
    secrets:
      - openldap_admin_password
    environment:
      SLAPD_USER: 'admin'
      SLAPD_PASSWORD: /run/secrets/openldap_admin_password
      SLAPD_DOMAIN: 'dc=surfuni,dc=org'
    networks:
      - dev-net
    #volumes:
      #- /mnt/nfs/nfsdlo/$STACK_NETWORK/openldap-0.1/conf:/etc/openldap
      #- /mnt/nfs/nfsdlo/$STACK_NETWORK/openldap-0.1/data:/var/lib/openldap
    ports:
      - 389:389

secrets:
  openldap_admin_password:
    external: true

networks:
  dev-net:
    external: true
