version: '3.7'

services:
  openldap: 
    #image: openldap
    image: 192.87.106.18:56001/openldap:0.1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: any
    secrets:
      - openldap_admin_password
    environment:
      SLAPD_USER: 'admin'
      SLAPD_PASSWORD: /run/secrets/openldap_admin_password
      SLAPD_DOMAIN: 'dc=surfuni,dc=org'
    networks:
      - $STACK_NETWORK
    volumes:
      #- $PWD/data/conf:/etc/openldap
      #- $PWD/data/data:/var/lib/openldap
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/conf:/etc/openldap
      - /mnt/nfs/nfsdlo/$STACK_NETWORK/$STACK_SERVICE/$STACK_VERSION/data:/var/lib/openldap
    ports:
      - $STACK_PORT:389

  ldaputils:
    #image: ldaputils
    image: 192.87.106.18:56001/ldaputils:0.1

    # ENV WERKT NIET VANUIT COMPOSE 
    # test: (levert niet de juiste $HOME): 
    #command: ["sh", "-c", "env;echo $HOME"]

    # dit zou handig zijn:
    #command: ["sh", "-c", "sleep 10; env; ldapadd -D \"cn=$SLAPD_USER,$SLAPD_DOMAIN\" -w $SLAPD_PASSWORD -p $SLAPD_PORT -h $SLAPD_HOST -f /provision/provision.ldif"]

    # for now, expose PASSWORD (don't!!!) 
    # command: ["sh", "-c", "sleep 10; env; ldapadd -D \"cn=admin,dc=surfuni,dc=org\" -w PASSWORD -p 389 -h 194.171.175.198 -f /provision/provision.ldif"]

    # solution: start script (works with env)
    command: [ "sh", "-c", "sleep 100;/provision/provision.sh"]

    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      restart_policy:
        condition: none
    secrets:
      - openldap_admin_password
    environment:
      SLAPD_USER: 'admin'
      SLAPD_PASSWORD: /run/secrets/openldap_admin_password
      SLAPD_DOMAIN: 'dc=surfuni,dc=org'
      SLAPD_HOST: '192.87.106.21'
      SLAPD_PORT: $STACK_PORT
    networks:
      - $STACK_NETWORK
    volumes:
      - $PWD/provision:/provision

secrets:
  openldap_admin_password:
    external: true

networks:
  dev-net:
    external: true
  test-net:
    external: true
  exp-net:
    external: true
